spring:
  redis:
    host: 107.175.194.157
    password: zxcv123321AZ
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: J3Bs?j6Gt6;R
    url: jdbc:mysql://107.175.194.157:3306/ae_prod?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&allowPublicKeyRetrieval=true&useSSL=false&&rewriteBatchedStatements=true