spring:
  redis:
    host: 192.210.197.111
    port: 6379
    password: zxcv123321AZ
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: zxcv123321AZ
    url: jdbc:mysql://192.210.197.111:3306/ae_prod?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&allowPublicKeyRetrieval=true&useSSL=false&&rewriteBatchedStatements=true