spring:
  redis:
    host: 107.175.194.157
    password: ${REDIS_PASSWORD}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${MYSQL_PASSWORD}
    url: jdbc:mysql://107.175.194.157:3306/ae_prod?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&allowPublicKeyRetrieval=true&useSSL=false&&rewriteBatchedStatements=true