# 建库
CREATE DATABASE ae_prod;
use ae_prod;
# 用户信息表
DROP TABLE IF EXISTS AE_USER;
CREATE TABLE `AE_USER` (
    ID BIGINT NOT NULL PRIMARY KEY COMMENT '主键ID',
    ACCOUNT VARCHAR(31) NOT NULL DEFAULT '' COMMENT '用户账号',
    `PASSWORD` VARCHAR(31) NOT NULL DEFAULT '' COMMENT '用户密码',
    USER_NAME VARCHAR(31) NOT NULL DEFAULT '' COMMENT '用户昵称',
    GMT_CREATE DATETIME COMMENT '创建时间',
    GMT_MODIFIED DATETIME COMMENT '修改时间',
    DELETED TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT '用户信息表';

# 角色表
DROP TABLE IF EXISTS AE_ROLE;
CREATE TABLE `AE_ROLE` (
    ID BIGINT NOT NULL PRIMARY KEY COMMENT '主键ID',
    ROLE VARCHAR(31) NOT NULL DEFAULT '' COMMENT '角色',
    GMT_CREATE DATETIME COMMENT '创建时间',
    GMT_MODIFIED DATETIME COMMENT '修改时间',
    DELETED TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT '用户信息表';

# 用户角色表
DROP TABLE IF EXISTS AE_USER_ROLE;
CREATE TABLE `AE_USER_ROLE` (
    ID BIGINT NOT NULL PRIMARY KEY COMMENT '主键ID',
    USER_ID BIGINT NOT NULL COMMENt '用户ID',
    ROLE_ID BIGINT NOT NULL COMMENt '角色ID',
    GMT_CREATE DATETIME COMMENT '创建时间',
    GMT_MODIFIED DATETIME COMMENT '修改时间',
    DELETED TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT '用户信息表';

# 权限表
DROP TABLE IF EXISTS AE_PERMISSION;
CREATE TABLE `AE_PERMISSION` (
    ID BIGINT NOT NULL PRIMARY KEY COMMENT '主键ID',
    PERMISSION VARCHAR(31) NOT NULL DEFAULT '' COMMENt '权限名称',
    GMT_CREATE DATETIME COMMENT '创建时间',
    GMT_MODIFIED DATETIME COMMENT '修改时间',
    DELETED TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT '用户信息表';

# 角色权限表
DROP TABLE IF EXISTS AE_ROLE_PERMISSION;
CREATE TABLE `AE_ROLE_PERMISSION` (
    ID BIGINT NOT NULL PRIMARY KEY COMMENT '主键ID',
    ROLE_ID BIGINT NOT NULL COMMENt '角色ID',
    PERMISSION_ID BIGINT NOT NULL  COMMENt '权限ID',
    GMT_CREATE DATETIME COMMENT '创建时间',
    GMT_MODIFIED DATETIME COMMENT '修改时间',
    DELETED TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT '用户信息表';

# 用户权限表
DROP TABLE IF EXISTS AE_USER_PERMISSION;
CREATE TABLE `AE_USER_PERMISSION` (
    ID BIGINT NOT NULL PRIMARY KEY COMMENT '主键ID',
    USER_ID BIGINT NOT NULL COMMENt '角色ID',
    PERMISSION_ID BIGINT NOT NULL  COMMENt '权限ID',
    GMT_CREATE DATETIME COMMENT '创建时间',
    GMT_MODIFIED DATETIME COMMENT '修改时间',
    DELETED TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT '用户信息表';


# GAME信息表
DROP TABLE IF EXISTS AE_GAME;
CREATE TABLE `AE_GAME` (
    ID BIGINT NOT NULL PRIMARY KEY COMMENT '主键ID',
    NAME VARCHAR(31) NOT NULL COMMENT 'Game名称',
    DESCRIPTION VARCHAR(127) NOT NULL DEFAULT '' COMMENT 'Game描述',
    JS_SCRIPT TEXT COMMENT '加密解密脚本文件',
    ARCHIVE_STRUCTURE TEXT COMMENT '存档结构信息',
    HEADER VARCHAR(255) NOT NULL DEFAULT '' COMMENT 'Header信息',
    GMT_CREATE DATETIME COMMENT '创建时间',
    GMT_MODIFIED DATETIME COMMENT '修改时间',
    DELETED TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT 'Game信息表';

# GAME 渠道信息表 -- 设计中
DROP TABLE IF EXISTS AE_GAME_TYPE;
CREATE TABLE `AE_GAME_TYPE` (
    ID BIGINT NOT NULL PRIMARY KEY COMMENT '主键ID'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT 'Game渠道信息表';

# 用户Game信息表 todo: 待完善
DROP TABLE IF EXISTS AE_USER_GAME;
CREATE TABLE `AE_USER_GAME` (
    ID BIGINT NOT NULL PRIMARY KEY COMMENT '主键ID',
    USER_ID BIGINT NOT NULL COMMENT '用户ID',
    GAME_ID BIGINT NOT NULL COMMENT 'Game ID',
    LOGIN_PARAM VARCHAR(1023)  COMMENT '登录JSON信息',
    USER_DATA_PARAM VARCHAR(1023) COMMENT '获取用户存档信息',
    GMT_CREATE DATETIME COMMENT '创建时间',
    GMT_MODIFIED DATETIME COMMENT '修改时间',
    DELETED TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT 'Game信息表';

# 用户登录信息
DROP TABLE IF EXISTS AE_USER_TOKEN;
CREATE TABLE `AE_USER_TOKEN` (
    ID BIGINT NOT NULL PRIMARY KEY COMMENT '主键ID',
    USER_ID VARCHAR(31) NOT NULL COMMENT '用户ID',
    GAME_ID VARCHAR(127) NOT NULL DEFAULT '' COMMENT 'Game ID',
    TOKEN VARCHAR(511) NOT NULL DEFAULT '' COMMENT '唯一凭证',
    GMT_CREATE DATETIME COMMENT '创建时间',
    GMT_MODIFIED DATETIME COMMENT '修改时间',
    DELETED TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT '用户登录信息表';

# 用户存档表
DROP TABLE IF EXISTS AE_USER_ARCHIVE;
CREATE TABLE `AE_USER_ARCHIVE` (
    ID BIGINT NOT NULL PRIMARY KEY COMMENT '主键ID',
    USER_ID BIGINT NOT NULL COMMENT '用户ID',
    GAME_ID BIGINT NOT NULL COMMENT '游戏ID',
    ARCHIVE_DATA TEXT COMMENT '存档信息',
    VERSION TINYINT NOT NULL DEFAULT 1 COMMENT '存档版本',
    GMT_CREATE DATETIME COMMENT '创建时间',
    GMT_MODIFIED DATETIME COMMENT '修改时间',
    DELETED TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT '用户存档表';

# 游戏存档结构部分表
DROP TABLE IF EXISTS AE_GAME_ARCHIVE_PART;
CREATE TABLE `AE_GAME_ARCHIVE_PART` (
    ID BIGINT NOT NULL PRIMARY KEY COMMENT '主键ID',
    GAME_ID BIGINT NOT NULL COMMENT 'Game ID',
    `KEY` VARCHAR(63) NOT NULL DEFAULT '' COMMENT '存档中对应字段',
    LABEL VARCHAR(31) NOT NULL DEFAULT '' COMMENT '存档中对应字段含义',
    `ENABLE` TINYINT NOT NULL DEFAULT 1 COMMENT '是否启用',
    SPECIAL VARCHAR(255) NOT NULL DEFAULT '' COMMENT '特殊处理',
    GMT_CREATE DATETIME COMMENT '创建时间',
    GMT_MODIFIED DATETIME COMMENT '修改时间',
    DELETED TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT '游戏存档结构部分表';

# 游戏物品表
DROP TABLE IF EXISTS AE_GAME_ITEM;
CREATE TABLE `AE_GAME_ITEM` (
    ID BIGINT NOT NULL PRIMARY KEY COMMENT '主键ID',
    GAME_ID BIGINT NOT NULL COMMENT 'Game ID',
    ITEM_ID VARCHAR(63) NOT NULL DEFAULT '' COMMENT '物品ID',
    LABEL VARCHAR(31) NOT NULL DEFAULT '' COMMENT '物品名称',
    ENABLE TINYINT NOT NULL DEFAULT 1 COMMENT '是否启用',
    URL VARCHAR(255) NOT NULL DEFAULT '' COMMENT '物品图标路径',
    GMT_CREATE DATETIME COMMENT '创建时间',
    GMT_MODIFIED DATETIME COMMENT '修改时间',
    DELETED TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT '游戏物品表';
